spring:
  profiles:
    active: local
  kafka:
    producer:
      bootstrap-servers: 192.168.0.103:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  name: data-collect-server